version: '2'

services:
#    odsupercomponent:
#        image: ${IMAGE}
#        network_mode: host
#        volumes:
#        - .:/opt/opendlv.data
#        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"
    
#    odcockpit:
#       image: ${IMAGE}
#       network_mode: host
#       environment:
#       - DISPLAY=$DISPLAY
#       volumes:
#       - /tmp/.X11-unix:/tmp/.X11-unix
#       - .:/opt/opendlv.data
#       - ~/recordings:/opt/recordings
#       ipc: host
#       user: odv
#       depends_on:
#           - odsupercomponent
#       command: "/opt/od4/bin/odcockpit --cid=${CID}"

#    cfsd18-sensation-attention:
#        image: "attention:test"
#        network_mode: "host"
#        ipc: host
#        command: "cfsd18-sensation-attention --cid=${CID} --verbose --id=1 --xBoundary=4 --yBoundary=12 --groundLayerZ=-0.3 --coneHeight=1 --connectDistanceThreshold=0.4 --layerRangeThreshold=0.06 --minNumOfPointsForCone=2 --maxNumOfPointsForCone=80 --farConeRadiusThreshold=0.2 --nearConeRadiusThreshold=0.25 --zRangeThreshold=0.08 --inlierRangeThreshold=0.06 --dotThreshold=0.1 --inlierFoundThreshold=150 --numberOfIterations=10"

#    proxy-camera:
#        image: camalpine:camalpine #cproxy:cproxyv1
#        network_mode: host
#        group_add:
#            - video
#        ipc: host
#        devices:
#            - "/dev/video1:/dev/video0"
#        environment:
#            - DISPLAY=$DISPLAY
#        volumes:
#            - /tmp/.X11-unix:/tmp/.X11-unix
#            - "/dev/shm:/dev/shm"
#        ulimits:
#          memlock:
#            soft: 12128256
#            hard: 12128256
#        command: "opendlv-device-camera-opencv --name=camera0 --bgr2rgb --cid=121 --camera=/dev/video0 --width=1344 --height=376 --bpp=24 --freq=15 --verbose"

    cfsd18-perception-imagerecorder:
        image: "imgrec:imgrecv0"
        network_mode: "host"
        ipc: host
        volumes:
        - ./images:/opt/images
        - ./timestamp:/opt/timestamp/
        command: "cfsd18-perception-imagerecorder --cid=121 --name=cam0 --width=1344 --height=376 --bpp=24 --verbose --id=1"


    
